#!/bin/bash
# Check layer boundary violations for TS/JS projects
# Generated by harness-engineering based on engineering-structure.md
FILE="$1"

# Determine which layer this file belongs to
# (Based on directory structure detected in Phase 1)
LAYER=""
case "$FILE" in
  */routes/*|*/pages/*|*/app/*)   LAYER="route" ;;
  */services/*)                    LAYER="service" ;;
  */models/*|*/entities/*)         LAYER="model" ;;
  */repositories/*|*/db/*)         LAYER="repository" ;;
  */adapters/*|*/clients/*)        LAYER="adapter" ;;
  *)                               exit 0 ;;  # Unknown layer, skip
esac

# Check forbidden imports per layer
# (Generated from Layer Boundaries table in engineering-structure.md)
case "$LAYER" in
  route)
    # Routes must not import directly from repository/adapter
    if grep -qE "from ['\"].*/(repositories|adapters|db)/" "$FILE" 2>/dev/null; then
      echo "LAYER VIOLATION: Route layer cannot import from repository/adapter layer"
      echo "File: $FILE"
      echo "Fix: Route should call service, service calls repository"
      exit 1
    fi
    ;;
  service)
    # Services must not import from route layer
    if grep -qE "from ['\"].*/(routes|pages|app)/" "$FILE" 2>/dev/null; then
      echo "LAYER VIOLATION: Service layer cannot import from route layer"
      echo "File: $FILE"
      exit 1
    fi
    ;;
esac

exit 0
